import {
  calculator1,
  calculator2,
  calculator3,
  calculator4,
  movielist1,
  movielist2,
  notToDo1,
  notToDo12,
  ft1,
  ft2,
  habitTracker,
} from "./prjectImages";

export const projectsData = [
  {
    id: 1,
    image: calculator1,
    transitionImage: calculator2,
    title: "Simple Calculator",
    codeLink: "https://github.com/bishalk21/JS_Calculator",
    liveLink: "https://bishalk21.github.io/JS_Calculator/",
  },
  {
    id: 2,
    image: calculator3,
    transitionImage: calculator4,
    title: "React Prank Calculator",
    codeLink: "https://github.com/bishalk21/react-prank-calculator",
    liveLink: "https://react-prank-calculator-sigma.vercel.app/",
  },
  {
    id: 3,
    image: movielist1,
    transitionImage: movielist2,
    title: "My Movie List",
    codeLink: "https://github.com/bishalk21/movie-app",
    liveLink: "https://movie-app-bishalk21.vercel.app/",
  },
  {
    id: 4,
    image: notToDo1,
    transitionImage: notToDo12,
    title: "My To Do List App",
    codeLink: "https://github.com/bishalk21/FS-not-to-do-app",
    liveLink: "https://not-to-do-list-app.herokuapp.com/",
  },
  {
    id: 5,
    image: ft1,
    transitionImage: ft2,
    title: "My Finance Tracker",
    codeLink: "https://github.com/bishalk21/my-finance-tracker",
    liveLink: "https://my-finance-tracker.herokuapp.com/",
  },

  {
    id: 6,
    image: habitTracker,
    transitionImage: habitTracker,
    title: "Habit Tracker",
    codeLink: "https://github.com/bishalk21/habit-tracker-system",
    liveLink: "https://bishalk21.github.io/habit-tracker-system/",
  },
];
